language: node_js
node_js:
  - "node"

before_script:
  - npm install
script:
  - npm run build

after_script:
  - if [ "$TRAVIS_BRANCH" = "develop" ]; then npm run deploy:dev;
    fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then npm run deploy:prod;
    fi
