backend:
  name: github
  repo: lucbpz/balazos-web
  branch: master
  base_url: https://us-central1-balazosdirecto.cloudfunctions.net
  auth_endpoint: /oauth/auth

media_folder: static/img
public_folder: /img

collections:
  - name: "members"
    label: "Members"
    folder: "content/members"
    create: true
    slug: "members-{{name}}"
    editor:
      preview: false
    fields:
      - { label: "Order", name: "order", widget: "number" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Avatar", name: "avatar", widget: "image" }
      - { label: "Position", name: "position", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Socials Networks", name: "socials", widget: "list" }

  - name: "services"
    label: "Servicios"
    folder: "content/services"
    create: true
    slug: "servicios-{{order}}-{{title}}"
    editor:
      preview: false
    fields:
      - { label: "Order", name: "order", widget: "number" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "icon", name: "icon", widget: "image" }
      - { label: "Descripcion", name: "description", widget: "markdown" }

  - name: "references"
    label: "Referencias"
    folder: "content/references"
    create: true
    slug: "referencias-{{order}}-{{author}}"
    editor:
      preview: false
    fields:
      - { label: "Order", name: "order", widget: "number" }
      - { label: "Autor", name: "author", widget: "string" }
      - { label: "Avatar", name: "avatar", widget: "image" }
      - { label: "Descripcion", name: "description", widget: "markdown" }
